import { z } from "zod"
import type { WebhookSourceDefinition } from "@/lib/webhooks/sources/types"

const POSTRIDER_SOURCE = "postrider"
const POSTRIDER_MESSAGE_RECEIVED_EVENT_SLUG = "message-received"
const POSTRIDER_MESSAGE_RECEIVED_EVENT_TYPE = "message.received"
export const POSTRIDER_WEBHOOK_TEST_EVENT_TYPE = "webhook.test"

const POSTRIDER_WEBHOOK_DISPLAY = {
  providerName: "PostRider",
  endpointDescription: "message.received webhook endpoint",
  setupInstruction: "Copy this URL into PostRider when creating the webhook.",
  verificationInstruction:
    "Paste the signing secret generated by PostRider. Control Center verifies X-PostRider-Signature with X-PostRider-Timestamp and the raw body.",
  secretPlaceholder: "Paste PostRider signing secret",
  routingTitle: "Message Routing",
  routingDescription: "When message.received arrives",
  eventsDescription: "Recent PostRider webhook traffic",
} as const

const postriderInboxSchema = z.object({
  id: z.string(),
  address: z.string().email(),
  name: z.string(),
})

export const postriderMessageReceivedSchema = z.object({
  schema_version: z.string(),
  event_type: z.literal(POSTRIDER_MESSAGE_RECEIVED_EVENT_TYPE),
  event_id: z.string(),
  message: z.object({
    id: z.string(),
    inbox_id: z.string().optional(),
    rfc_message_id: z.string().nullable().optional(),
    from: z.object({
      email: z.string().email(),
      name: z.string().nullable().optional(),
    }),
    subject: z.string().nullable().optional(),
    detected_type: z.string().nullable().optional(),
    codes_count: z.number().int().nonnegative(),
    links_count: z.number().int().nonnegative(),
    received_at: z.string().datetime(),
  }),
  inbox: postriderInboxSchema.optional(),
})

export const postriderWebhookTestSchema = z.object({
  schema_version: z.string(),
  event_type: z.literal(POSTRIDER_WEBHOOK_TEST_EVENT_TYPE),
  event_id: z.string(),
  inbox: postriderInboxSchema.optional(),
  test: z.literal(true),
})

export const postriderWebhookEventSchema = z.discriminatedUnion("event_type", [
  postriderMessageReceivedSchema,
  postriderWebhookTestSchema,
])

export type PostriderMessageReceivedPayload = z.infer<typeof postriderMessageReceivedSchema>
export type PostriderWebhookEventPayload = z.infer<typeof postriderWebhookEventSchema>

export function getPostriderTargetAgent(payload: PostriderMessageReceivedPayload) {
  return payload.inbox?.name || payload.inbox?.address || null
}

export function getPostriderMessageId(payload: PostriderMessageReceivedPayload) {
  return payload.message.id
}

export function getPostriderSender(payload: PostriderMessageReceivedPayload) {
  return {
    email: payload.message.from.email,
    name: payload.message.from.name ?? null,
  }
}

export function getPostriderReceivedAt(payload: PostriderMessageReceivedPayload) {
  return payload.message.received_at
}

export function getPostriderCodesCount(payload: PostriderMessageReceivedPayload) {
  return payload.message.codes_count
}

export function getPostriderLinksCount(payload: PostriderMessageReceivedPayload) {
  return payload.message.links_count
}

export function parsePostriderMessageReceived(payload: unknown) {
  return postriderMessageReceivedSchema.safeParse(payload)
}

export function parsePostriderWebhookEvent(payload: unknown) {
  return postriderWebhookEventSchema.safeParse(payload)
}

export const postriderWebhookSource: WebhookSourceDefinition = {
  source: POSTRIDER_SOURCE,
  eventSlug: POSTRIDER_MESSAGE_RECEIVED_EVENT_SLUG,
  primaryEventType: POSTRIDER_MESSAGE_RECEIVED_EVENT_TYPE,
  signatureHeaders: ["x-postrider-signature", "x-webhook-signature"],
  timestampHeaders: ["x-postrider-timestamp", "x-webhook-timestamp"],
  display: POSTRIDER_WEBHOOK_DISPLAY,
  parseEvent(payload: unknown) {
    const parsed = parsePostriderWebhookEvent(payload)
    if (!parsed.success) return { success: false, reason: parsed.error.issues[0]?.message }

    const data = parsed.data
    if (data.event_type === POSTRIDER_WEBHOOK_TEST_EVENT_TYPE) {
      return {
        success: true,
        data: {
          eventType: data.event_type,
          externalId: data.event_id,
          targetAgent: data.inbox?.name || data.inbox?.address || null,
          displayTitle: "Webhook test",
          payload: data,
          status: "ignored",
          handledAt: new Date(),
          shouldRoute: false,
          responseStatus: "test_received",
        },
      }
    }

    return {
      success: true,
      data: {
        eventType: data.event_type,
        externalId: data.event_id,
        providerMessageId: getPostriderMessageId(data),
        targetAgent: getPostriderTargetAgent(data),
        displayTitle: data.message.subject ?? "(no subject)",
        payload: data,
        status: "open",
        shouldRoute: true,
        responseStatus: "open",
      },
    }
  },
}
