import { z } from "zod"
import type { WebhookSourceDefinition } from "@/lib/webhooks/sources/types"

const POSTRIDER_SOURCE = "postrider"
const POSTRIDER_MESSAGE_RECEIVED_EVENT_SLUG = "message-received"
const POSTRIDER_MESSAGE_RECEIVED_EVENT_TYPE = "message.received"
export const POSTRIDER_WEBHOOK_TEST_EVENT_TYPE = "webhook.test"

const POSTRIDER_WEBHOOK_DISPLAY = {
  providerName: "PostRider",
  endpointDescription: "message.received webhook endpoint",
  setupInstruction: "Copy this URL into PostRider when creating the webhook.",
  verificationInstruction:
    "Paste the signing secret generated by PostRider. Control Center verifies X-PostRider-Signature with X-PostRider-Timestamp and the raw body.",
  secretPlaceholder: "Paste PostRider signing secret",
  routingTitle: "Message Routing",
  routingDescription: "When message.received arrives",
  eventsDescription: "Recent PostRider webhook traffic",
} as const

const postriderInboxSchema = z.object({
  id: z.string(),
  address: z.string().email(),
  name: z.string(),
})

export const postriderMessageReceivedSchema = z.object({
  type: z.literal("event"),
  event_type: z.literal(POSTRIDER_MESSAGE_RECEIVED_EVENT_TYPE),
  event_id: z.string(),
  message: z.object({
    inbox_id: z.string(),
    message_id: z.string(),
    timestamp: z.string().datetime(),
    from: z.string().email(),
    from_name: z.string().nullable().optional(),
    to: z.array(z.string().email()),
    subject: z.string().nullable(),
    detected_type: z.string().nullable().optional(),
    codes: z.array(z.string()),
    links: z.array(
      z.object({
        label: z.string().nullable().optional(),
        url: z.string().url(),
      }),
    ),
  }),
  inbox: postriderInboxSchema,
})

export const postriderWebhookTestSchema = z.object({
  type: z.literal("event"),
  event_type: z.literal(POSTRIDER_WEBHOOK_TEST_EVENT_TYPE),
  event_id: z.string(),
  inbox: postriderInboxSchema,
  test: z.literal(true),
})

export const postriderWebhookEventSchema = z.discriminatedUnion("event_type", [
  postriderMessageReceivedSchema,
  postriderWebhookTestSchema,
])

export type PostriderMessageReceivedPayload = z.infer<typeof postriderMessageReceivedSchema>
export type PostriderWebhookEventPayload = z.infer<typeof postriderWebhookEventSchema>

export function getPostriderTargetAgent(payload: PostriderMessageReceivedPayload) {
  return payload.inbox.name || payload.inbox.address
}

export function parsePostriderMessageReceived(payload: unknown) {
  return postriderMessageReceivedSchema.safeParse(payload)
}

export function parsePostriderWebhookEvent(payload: unknown) {
  return postriderWebhookEventSchema.safeParse(payload)
}

export const postriderWebhookSource: WebhookSourceDefinition = {
  source: POSTRIDER_SOURCE,
  eventSlug: POSTRIDER_MESSAGE_RECEIVED_EVENT_SLUG,
  primaryEventType: POSTRIDER_MESSAGE_RECEIVED_EVENT_TYPE,
  signatureHeaders: ["x-postrider-signature", "x-webhook-signature"],
  timestampHeaders: ["x-postrider-timestamp", "x-webhook-timestamp"],
  display: POSTRIDER_WEBHOOK_DISPLAY,
  parseEvent(payload: unknown) {
    const parsed = parsePostriderWebhookEvent(payload)
    if (!parsed.success) return { success: false, reason: parsed.error.issues[0]?.message }

    const data = parsed.data
    if (data.event_type === POSTRIDER_WEBHOOK_TEST_EVENT_TYPE) {
      return {
        success: true,
        data: {
          eventType: data.event_type,
          externalId: data.event_id,
          targetAgent: data.inbox.name || data.inbox.address,
          displayTitle: "Webhook test",
          payload: data,
          status: "ignored",
          handledAt: new Date(),
          shouldRoute: false,
          responseStatus: "test_received",
        },
      }
    }

    return {
      success: true,
      data: {
        eventType: data.event_type,
        externalId: data.event_id,
        providerMessageId: data.message.message_id,
        targetAgent: getPostriderTargetAgent(data),
        displayTitle: data.message.subject ?? "(no subject)",
        payload: data,
        status: "pending",
        shouldRoute: true,
        responseStatus: "pending",
      },
    }
  },
}
